# global configs
lidar: VPL16
log_to_file: false
log_path: /home/lf/catkin_ws/src/oh_my_loam/.log
vis: true

# configs for feature points extractor
extractor_config:
  min_point_num: 66
  vis: false
  sharp_corner_point_num: 2
  corner_point_num: 20
  flat_surf_point_num: 4
  surf_point_num: 3 ## useless currently
  corner_point_curvature_thres: 0.5
  surf_point_curvature_thres: 0.5
  neighbor_point_dist_thres: 0.05
  downsample_voxel_size: 0.3

odometry_config: 
  icp_iter_num : 2
  match_dist_sq_thresh: 1
  vis: true