# global configs
lidar: VPL16
log_to_file: false
log_path: /data/log/oh_my_loam
vis: true

# configs for extractor
extractor_config:
  vis: false
  verbose: true
  min_point_num: 66
  sharp_corner_point_num: 2
  corner_point_num: 20
  flat_surf_point_num: 4
  surf_point_num: 20
  corner_point_curvature_th: 0.5
  surf_point_curvature_th: 0.5
  neighbor_point_dist_th: 0.1
  downsample_voxel_size: 0.3

# configs for odometer
odometer_config:
  vis: true
  verbose: false
  icp_iter_num: 2
  match_dist_sq_th: 1

# configs for mapper
mapper_config:
  vis: false
